---
title: "LoPresti2019_DataAnalysis"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r, include=FALSE}
knitr::opts_chunk$set(fig.width = 15, fig.height = 5, warning=FALSE, message=FALSE,
                      root.dir = "/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/")
```



#######################
## IMPORT LIBRAIRIES ##
#######################
```{r library-import, echo=FALSE}
library(dada2) # manage fastq file

library(ShortRead) # manage fastq file

library(Biostrings) # to manage dna sequences as strings

library(seqTools) # analyse read length in fastq file

library(phyloseq) # for phyloseq object

library(ggplot2) # for plots
library(ggrepel)

library(data.table)

library(plyr)
library(dplyr)

library("doParallel")

library("foreach")

library("DECIPHER") # for phylogenetic tree
library(ips)
library("phangorn")

library("plotly") # plot 3D

library("microbiome") # for centered log-ratio

library("coda") # Aitchison distance

library("coda.base") # Aitchison distance

library("vegan") # NMDS

library(pheatmap) # for heat map
```


#################
## IMPORT DATA ##
#################

XXXX
```{r TO-DELETE, eval = FALSE, echo = TRUE}
# Import metadata
metadata_table <- read.csv("/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/LoPresti_SraRunTable.csv")
table(metadata_table$host_disease) # look at number of IBS vs HC
table(metadata_table$env_material) # look at number of stool vs mucosa

# Keep only relevant metadata
metadata_table <- metadata_table[, c("Run", "host_disease", "gastrointest_disord", "env_material",
                                     "Sample.Name", "Host_Age", "host_sex")]
rownames(metadata_table) <- metadata_table$Run # assign sample names as row names

metadata_table$host_disease <- as.character(metadata_table$host_disease) # host_disease is of class "factor", transform it to characters
metadata_table$gastrointest_disord <- as.character(metadata_table$gastrointest_disord) # gastrointest_disord is of class "factor", transform it to characters

metadata_table$host_disease[metadata_table$host_disease == "Healthy subject"] <- "Healthy" # replace host_disease "none" to "healthy"
metadata_table$host_disease[metadata_table$host_disease == "Irritable Bowel Syndrome"] <- "IBS"

metadata_table$gastrointest_disord[metadata_table$gastrointest_disord == "Absence"] <- "HC"
metadata_table$gastrointest_disord[metadata_table$gastrointest_disord == "Alternating constipation and diarrhea"] <- "IBS-M"
metadata_table$gastrointest_disord[metadata_table$gastrointest_disord == "diarrhea"] <- "IBS-D"
metadata_table$gastrointest_disord[metadata_table$gastrointest_disord == "constipation"] <- "IBS-C"

metadata_table$Sample.Name <- gsub("\\.A$", '', metadata_table$Sample.Name)
metadata_table$Sample.Name <- gsub("\\A$", '', metadata_table$Sample.Name)

colnames(metadata_table) <- c('Run', 'host_disease', 'host_subtype', 'sample_type', 'individual', 'host_age', 'host_sex')

metadata_table$author <- "LoPresti"
metadata_table$sequencing_tech <- "454 pyrosequencing"
metadata_table$variable_region <- "V1-V3"

saveRDS(metadata_table, "/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/metadata_final.rds")


#_________________________________________________________________________
# Import OTU table (rows: sample names // columns: sequence variants)
seqtable.nochim <- readRDS("/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/ASVtable_final.rds")
dim(seqtable.nochim) # should have 163 samples and 1198 ASV
rownames(seqtable.nochim) <- gsub(".fastq.gz","", rownames(seqtable.nochim)) # remove the .fastq.gz extension in sample names

# Import Taxonomic table (rows: sequence variants // columns: Kingdom, Phylum, Class, ...)
taxa <- readRDS("/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/taxa_final.rds")
dim(taxa)
```
XXXX

```{r}
dim(test)
test <- metadata_table[!duplicated(metadata_table$individual),]
table(test$individual)
unique(metadata_table$individual)

# Age
mean(test[test$host_disease == "IBS", "host_age"])
sd(test[test$host_disease == "IBS", "host_age"])
max(test[test$host_disease == "IBS", "host_age"])

mean(test[test$host_disease == "Healthy", "host_age"])
sd(test[test$host_disease == "Healthy", "host_age"])
max(test[test$host_disease == "Healthy", "host_age"])

wilcox.test(test[test$host_disease == "IBS", "host_age"],
            test[test$host_disease == "Healthy", "host_age"])

# Gender
table(test[test$host_disease == "IBS", "host_sex"])
30/44
table(test[test$host_disease == "Healthy", "host_sex"])
20/47

chisq.test(data.frame("Female" = c(30,20),
                      "Male" = c(14,27)))
```


```{r import-for-pdf, echo = FALSE}
metadata_table <- readRDS("/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/metadata_final.rds")
physeq <- readRDS("/Users/scarcy/Desktop/Praktikum/Data/OutputPhangorn/physeq_lopresti.rds")
physeq_best <- readRDS("/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/Rproject_DataAnalysis/physeq_best.rds")
physeq.rel <- readRDS("/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/Rproject_DataAnalysis/physeq_relative.rds")
physeq.clr <- readRDS("/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/Rproject_DataAnalysis/physeq_clr.rds")

# Distance methods
dist_methods <- unlist(distanceMethodList)
dist_methods <- dist_methods[-which(dist_methods=="ANY")] # Remove the user-defined distance
dist_methods <- dist_methods[-c(1,15,18)] #remove unweighted unifrac, mountford, chao (not gonna work on pseudocounts)
dist_methods <- dist_methods[1:16] #keep only the 16 first methods (remove the beta diversity distances)

# For heatmaps: have group color
mat_col <- data.frame(group = metadata_table[,"host_disease"],
                      sampleType = metadata_table[,"env_material"],
                      subtype = metadata_table[,"gastrointest_disord"])
rownames(mat_col) <- rownames(metadata_table)
```



############################
## CREATE PHYLOSEQ OBJECT ##
############################

```{r phyloseq-object, eval = FALSE, echo = TRUE}
#____________________________________________________________________
# OTU TABLE, TAXA TABLE AND METADATA
physeq <- phyloseq(otu_table(seqtable.nochim, taxa_are_rows=FALSE), # by default, in otu_table the sequence variants are in rows
                  sample_data(metadata_table), 
                  tax_table(taxa))

#____________________________________________________________________
# PHYLOGENETIC TREE

# Multiple-sequence alignment (know which regions are conserved/different to be able to do the phylogeny)
seqs <- getSequences(seqtable.nochim) # get the sequence variants (the ASVs)
names(seqs) <- seqs # This propagates to the tip labels of the tree
alignment <- AlignSeqs(DNAStringSet(seqs), anchor=NA) # by default, anchor = 0.7 which means that 70% of sequences must share a common region to anchor the alignment space.

# Construct a neighbor-joining tree
phang.align <- phyDat(as(alignment, "matrix"), type="DNA") # transform the aligned DNA sequences into a phyDat (phangorn) object
dm <- dist.ml(phang.align) # compute pairwise distance between DNA sequences (with the Jukes-Cantor estimate of the evolutionary distance)
treeNJ <- NJ(dm) # create a neighbor-joining tree estimation based on the distance matrix
fit <- pml(treeNJ, data=phang.align) # get the likelihood of the phylogenetic tree given the sequence alignment (then we'll optimize it)

## negative edges length changed to 0!

# Fit a generalized time-reversible with gamma rate variation (GTR+G+I)
fitGTR <- update(fit, k=4, inv=0.2)
fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE, # gamma rate and proportion of variable size get optimized
                      rearrangement = "stochastic", control = pml.control(trace = 0)) # (trace = 0) don't show output during optimization
# stochastic tree rearrangement

## Message displayed : "I unrooted the tree"

# Add tree to physeq
physeq <- merge_phyloseq(physeq, phy_tree(fitGTR$tree))
```

```{r plot-tree, fig.height = 6, fig.width = 10}
# Look at the tree
plot_tree(physeq, color = "host_disease", ladderize="left")
```


```{r phyloseq-object-2, eval = FALSE, echo = TRUE}
#____________________________________________________________________
# GIVE SURNAMES TO OTUs

# Give surnames to sequence variants & store the sequence variants in "refseq" in the phyloseq object
dna <- DNAStringSet(taxa_names(physeq)) # get the sequence variants (ASVs)
names(dna) <- taxa_names(physeq) # no idea what this does
physeq <- merge_phyloseq(physeq, dna) # store the dna sequences in the refseq of the phyloseq object
taxa_names(physeq) <- paste0("OTU", seq(ntaxa(physeq))) # replace the whole dna sequences in the taxa_names by a surname OTU1, OTU2, etc.


# Save physeq object
saveRDS(physeq, "/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/Rproject_DataAnalysis/physeq.rds")
saveRDS(physeq, "/Users/scarcy/Desktop/Praktikum/Data/Rproject_COMBINE/physeq_lopresti.rds")
```



######################################
## ABSOLUTE AND RELATIVE ABUNDANCES ##
######################################
```{r plot-abundances, echo = TRUE, fig.height = 6}
# Plot Phylum
plot_bar(physeq, fill = "Phylum") + facet_wrap("env_material", scales="free") +
  theme(axis.text.x = element_text(size = 8))+
  labs(x = "Samples", y = "Total read count", title = "LoPresti dataset (2019)")+
  ylim(0,7000)
```


```{r}
# Replace "IBS-A" by "IBS-M"
sample_data(physeq)[sample_data(physeq)$gastrointest_disord == "IBS-A", "gastrointest_disord"] <- "IBS-M"
sample_data(physeq)
```


As many samples have a very low count number, we will remove samples that have less than 500 total reads


```{r plot-abundances-2, fig.height = 6}
physeq_best <- prune_samples(sample_sums(physeq)>=1000, physeq)
physeq_best
# Plot Phylum
plot_bar(physeq_best, fill = "Phylum") + facet_wrap("env_material", scales="free") +
  theme(axis.text.x = element_text(size = 8))+
  labs(x = "Samples", y = "Total read count", title = "LoPresti dataset (2019)")+
  ylim(0,7000)

# Relative abundance for Phylum
phylum.table <- physeq_best %>%
  tax_glom(taxrank = "Phylum") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt()                                             # Melt to long format

ggplot(phylum.table, aes(x = Sample.Name, y = Abundance, fill = Phylum))+
  facet_wrap(~ host_disease + env_material, scales = "free") + # scales = "free" removes empty lines
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(size = 8, angle = -90))+
  labs(x = "Individuals", y = "Relative abundance", title = "LoPresti dataset (2019)")

# Plot Class
plot_bar(physeq_best, fill = "Class")+ facet_wrap("host_disease", scales="free") +
  theme(axis.text.x = element_text(size = 8))+
  labs(x = "Samples", y = "Total read count", title = "LoPresti dataset (2019)")+
  ylim(0,7000)

# Relative abundance for Class
class.table <- physeq_best %>%
  tax_glom(taxrank = "Class") %>%                     # agglomerate at class level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt()                                             # Melt to long format

ggplot(class.table, aes(x = Sample, y = Abundance, fill = Class))+
  facet_wrap(~ host_disease, scales = "free") + # scales = "free" removes empty lines
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(size = 8, angle = -90))+
  labs(x = "Samples", y = "Relative abundance", title = "LoPresti dataset (2019)")
```


```{r plot-log-ratio, fig.height = 3, fig.width=7}
# Extract abundance only Bacteroidota and Firmicutes
bacter <- phylum.table[phylum.table[,'Phylum'] == 'Bacteroidota', c('Sample', 'Abundance', 'Phylum',
                                                                    'host_disease', 'gastrointest_disord', 'env_material')]
bacter <- bacter[order(bacter$Sample),] # order by sample name
firmi <- phylum.table[phylum.table[,'Phylum'] == 'Firmicutes', c('Sample', 'Abundance', 'Phylum',
                                                                    'host_disease', 'gastrointest_disord', 'env_material')]
firmi <- firmi[order(firmi$Sample),] # order by sample name

# Calculate log2 ratio Firmicutes/Bacteroidota
ratio_FB <- data.table('Sample' = bacter$Sample,
                       'host_disease' = bacter$host_disease,
                       'host_subtype' = bacter$gastrointest_disord,
                       'sample_type' = bacter$env_material,
                       'Bacteroidota' = bacter$Abundance,
                       'Firmicutes' = firmi$Abundance)
ratio_FB[,"Log_ratio_FB"] <- log2(ratio_FB[,"Firmicutes"] / ratio_FB[,"Bacteroidota"])

# Plot log2 ratio Firmicutes/Bacteroidota
par(mar = c(3, 10, 3, 10))
boxplot(data = ratio_FB, Log_ratio_FB ~ host_subtype, ylab = "Log2 Ratio Abundance", xlab = "", main = "Firmicutes to Bacteroidota ratio")

par(mar = c(3, 10, 3, 10))
boxplot(data = ratio_FB, Log_ratio_FB ~ sample_type, ylab = "Log2 Ratio Abundance", xlab = "", main = "Firmicutes to Bacteroidota ratio")
```

```{r statistics, echo = FALSE, eval = FALSE}
# Nb of samples and individuals
table(metadata_table$host_disease)
table(metadata_table$env_material)
table(metadata_table[metadata_table$env_material == 'stool',]$host_disease)

# Nb of counts per sample
max(sample_sums(physeq))
min(sample_sums(physeq))
median(sample_sums(physeq))

max(sample_sums(physeq_best))
min(sample_sums(physeq_best))
median(sample_sums(physeq_best))

# Nb of phyla & classes
table(taxa[,2])
table(taxa[,3])

# Take out the '.A' at the end of the Sample.Names
phylum.table$Sample.Name <- gsub("\\.A$", '', phylum.table$Sample.Name)
phylum.table$Sample.Name <- gsub("A$", '', phylum.table$Sample.Name)

metadata_table$Sample.Name <- gsub("\\.A$", '', metadata_table$Sample.Name)
metadata_table$Sample.Name <- gsub("A$", '', metadata_table$Sample.Name)
table(metadata_table[metadata_table$host_disease == 'Healthy',]$Sample.Name) # How many individuals do we have?

# Percentage of main phyla
mean(phylum.table[phylum.table[,'Phylum'] == 'Firmicutes', 'Abundance'])
mean(phylum.table[phylum.table[,'Phylum'] == 'Bacteroidota', 'Abundance'])
mean(phylum.table[phylum.table[,'Phylum'] == 'Proteobacteria', 'Abundance'])

# Percentage of main classes
mean(class.table[class.table[,'Class'] == 'Clostridia', 'Abundance'])
mean(class.table[class.table[,'Class'] == 'Bacteroidia', 'Abundance'])
mean(class.table[class.table[,'Class'] == 'Gammaproteobacteria', 'Abundance'])

```



```{r export-plots-1, eval = FALSE, echo = FALSE}

jpeg("./Plots/plot_phylum_absAbundance.jpg", width = 4000, height = 2000)
plot_bar(physeq, fill = "Phylum") + facet_wrap("host_disease", scales="free") +
  theme(axis.text.x = element_text(size = 20, angle = -90),
        axis.text.y = element_text(size = 30),
        legend.text = element_text(size = 50),
        axis.title = element_text(size = 50),
        title = element_text(size = 70),
        strip.text = element_text(size = 50))+
  labs(x = "Samples", y = "Total read count", title = "LoPresti dataset (2019)")+
  ylim(0,6500)
dev.off()

jpeg("./Plots/plot_phylum_absAbundance_BEST.jpg", width = 4000, height = 2000)
plot_bar(physeq_best, fill = "Phylum") + facet_wrap("host_disease", scales="free") +
  theme(axis.text.x = element_text(size = 20, angle = -90),
        axis.text.y = element_text(size = 30),
        legend.text = element_text(size = 50),
        axis.title = element_text(size = 50),
        title = element_text(size = 70),
        strip.text = element_text(size = 50))+
  labs(x = "Samples", y = "Total read count", title = "LoPresti dataset (2019)")+
  ylim(0,6500)
dev.off()

jpeg("./Plots/phylum_relAbundance.jpg", width = 4000, height = 2000)
ggplot(phylum.table, aes(x = Sample, y = Abundance, fill = Phylum))+
  facet_wrap(~ host_disease, scales = "free") + # scales = "free" removes empty lines
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(size = 20, angle = -90),
        axis.text.y = element_text(size = 30),
        legend.text = element_text(size = 50),
        axis.title = element_text(size = 50),
        title = element_text(size = 70),
        strip.text = element_text(size = 50))+
  labs(x = "Samples", y = "Relative abundance", title = "LoPresti dataset (2019)")
dev.off()

jpeg("./Plots/plot_phylum_relAbundance.jpg", width = 4000, height = 2000)
ggplot(phylum.table, aes(x = Sample.Name, y = Abundance, fill = Phylum))+
  facet_wrap(~ host_disease + env_material, scales = "free") + # scales = "free" removes empty lines
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(size = 20, angle = -90),
        axis.text.y = element_text(size = 30),
        legend.text = element_text(size = 50),
        axis.title = element_text(size = 50),
        title = element_text(size = 70),
        strip.text = element_text(size = 50))+
  labs(x = "Individuals", y = "Relative abundance", title = "LoPresti dataset (2019)")
dev.off()

jpeg("./Plots/plot_class_relAbundance.jpg", width = 4000, height = 2000)
ggplot(class.table, aes(x = Sample, y = Abundance, fill = Class))+
  facet_wrap(~ host_disease, scales = "free") + # scales = "free" removes empty lines
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(size = 20, angle = -90),
        axis.text.y = element_text(size = 30),
        legend.text = element_text(size = 50),
        axis.title = element_text(size = 50),
        title = element_text(size = 70),
        strip.text = element_text(size = 50))+
  labs(x = "Samples", y = "Relative abundance", title = "LoPresti dataset (2019)")
dev.off()

jpeg("./Plots/log2ratio_FirmBact.jpg", width = 1500, height = 2000)
ggplot(ratio_FB, aes(x = host_disease, y = Log_ratio_FB))+
  geom_boxplot(lwd = 2)+
  labs(x = "",  y = 'Log2 Firmicutes/Bacteroidota Abundance Ratio', title = "LoPresti dataset (2019)")+
  theme_classic()+
  theme(axis.text = element_text(size = 50),
        legend.text = element_text(size = 50),
        axis.title = element_text(size = 50),
        title = element_text(size = 50))
dev.off()

jpeg("./Plots/log2ratio_FirmBact_subtypes.jpg", width = 1500, height = 2000)
ggplot(ratio_FB, aes(x = host_subtype, y = Log_ratio_FB))+
  geom_boxplot(lwd = 2)+
  labs(x = "",  y = 'Log2 Firmicutes/Bacteroidota Abundance Ratio', title = "LoPresti dataset (2019)")+
  theme_classic()+
  theme(axis.text = element_text(size = 50),
        axis.text.x = element_text(angle = 45, vjust = 0.5),
        legend.text = element_text(size = 50),
        axis.title = element_text(size = 50),
        title = element_text(size = 50))+
  ylim(-3, 10)
dev.off()

jpeg("./Plots/log2ratio_FirmBact_sample.jpg", width = 1500, height = 2000)
ggplot(ratio_FB, aes(x = sample_type, y = Log_ratio_FB))+
  geom_boxplot(lwd = 2)+
  labs(x = "",  y = 'Log2 Firmicutes/Bacteroidota Abundance Ratio', title = "LoPresti dataset (2019)")+
  theme_classic()+
  theme(axis.text = element_text(size = 50),
        legend.text = element_text(size = 50),
        axis.title = element_text(size = 50),
        title = element_text(size = 50))
dev.off()

```



####################
## NORMALIZE DATA ##
####################

```{r normalize-data, eval = FALSE, echo = TRUE}
# REMOVE SAMPLES WITH LESS THAN 1000 COUNTS
physeq_best <-  prune_samples(sample_sums(physeq)>=1000, physeq)
physeq_best <- subset_taxa(physeq_best, !is.na(Phylum)) # remove the 5 NA Phyla
physeq_best

#____________________________________________________________________
# PHYLOSEQ OBJECT WITH NON-ZERO COMPOSITIONS
physeq.NZcomp <- physeq_best
otu_table(physeq.NZcomp)[otu_table(physeq.NZcomp) == 0] <- 0.5

# check the 0 values have been replaced
otu_table(physeq_best)[1:5,1:5]
otu_table(physeq.NZcomp)[1:5,1:5]

# transform into compositions
physeq.NZcomp <- transform_sample_counts(physeq.NZcomp, function(x) x / sum(x) ) # divide each count by the total number of counts (per sample)
sum(otu_table(physeq.NZcomp) < 0) # see how many negative values are present in the matrix
table(rowSums(otu_table(physeq.NZcomp))) # check if there is any row not summing to 1

# save the physeq.NZcomp object
saveRDS(physeq.NZcomp, "/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/Rproject_DataAnalysis/physeq_NZcomp.rds")

#____________________________________________________________________
# PHYLOSEQ OBJECT WITH RELATIVE COUNT (BETWEEN 0 AND 1)
physeq.rel <- physeq_best
physeq.rel <- transform_sample_counts(physeq.rel, function(x) x / sum(x) ) # divide each count by the total number of counts (per sample)

# check the counts are all relative
otu_table(physeq)[1:5, 1:5]
otu_table(physeq.rel)[1:5, 1:5]

# sanity check
sum(otu_table(physeq.rel) < 0) # see how many negative values are present in the matrix
sum(rowSums(otu_table(physeq.rel)) == 1) # check if there is any row not summing to 1

# save the physeq.rel object
saveRDS(physeq.rel, "/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/Rproject_DataAnalysis/physeq_relative.rds")

#____________________________________________________________________
# PHYLOSEQ OBJECT WITH COMMON-SCALE NORMALIZATION
physeq.CSN <- physeq_best
min(sample_sums(physeq.CSN)) # sanity check
physeq.CSN <- transform_sample_counts(physeq.CSN, function(x) (x*min(sample_sums(physeq.CSN))) / sum(x) ) # divide each count by the total number of counts (per sample)

# sanity check
sum(otu_table(physeq.CSN) < 0) # see how many negative values are present in the matrix
table(rowSums(otu_table(physeq.CSN))) # check if there is any row not summing to 1

# save the physeq.CSN object
saveRDS(physeq.CSN, "/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/Rproject_DataAnalysis/physeq_CSN.rds")


#____________________________________________________________________
# PHYLOSEQ OBJECT WITH CENTERED LOG RATIO COUNT
physeq.clr <- physeq_best
physeq.clr <- transform(physeq.clr, "clr") # the function adds pseudocounts itself

# Compare the otu tables in the original phyloseq object and the new one after CLR transformation
otu_table(physeq_best)[1:5, 1:5] # should contain absolute counts
otu_table(physeq.clr)[1:5, 1:5] # should all be relative

# save the physeq.rel object
saveRDS(physeq.clr, "/Users/scarcy/Desktop/Praktikum/Data/LoPresti_2019/Rproject_DataAnalysis/physeq_clr.rds")
```



#######################
## COMPUTE DISTANCES ##
#######################

```{r dist-thesis, fig.width = 15, fig.height = 4}
#____________________________________________________________________________________
# Measure distances
Distances <- function(){
  set.seed(123) # for unifrac, need to set a seed
  glom.UniF <-  UniFrac(physeq.rel, weighted=TRUE, normalized=TRUE) # weighted unifrac
  glom.ait <- distance(physeq.clr, method = 'euclidean') # aitchison
  glom.bray <- distance(physeq.CSN, method = "bray") # bray-curtis
  glom.can <- distance(physeq.NZcomp, method = "canberra") # canberra
  dist.list <- list("UniF" = glom.UniF, "Ait" = glom.ait, "Canb" = glom.can, "Bray" = glom.bray)
  
  return(dist.list)
}
#subset_samples(physeq.clr, sample_names(physeq.clr) != 'SRR5245605')

DistancesPlot <- function(d){
  plist <- NULL
  plist <- vector("list", 4)
  names(plist) <- c("Weighted Unifrac", "Aitchison", "Bray-Curtis", "Canberra")
  
  print("Unifrac")
  # Weighted UniFrac
  set.seed(123)
  iMDS.UniF <- ordinate(physeq.rel, "MDS", distance=d$UniF)
  plist[[1]] <- plot_ordination(physeq.rel, iMDS.UniF, color="host_disease")
  
  print("Aitchison")
  # Aitchison
  set.seed(123)
  iMDS.Ait <- ordinate(physeq.clr, "MDS", distance=d$Ait)
  plist[[2]] <- plot_ordination(physeq.clr, iMDS.Ait, color="host_disease")
  
  print("Bray")
  # Bray-Curtis
  set.seed(123)
  iMDS.Bray <- ordinate(physeq.CSN, "MDS", distance=d$Bray)
  plist[[3]] <- plot_ordination(physeq.CSN, iMDS.Bray, color="host_disease")
  
  print("Canberra")
  # Canberra
  set.seed(123)
  iMDS.Can <- ordinate(physeq.NZcomp, "MDS", distance=d$Can)
  plist[[4]] <- plot_ordination(physeq.NZcomp, iMDS.Can, color="host_disease")
  
  # Creating a dataframe to plot everything
  plot.df = ldply(plist, function(x) x$data)
  names(plot.df)[1] <- "distance"
  
  return(plot.df)
}

dist.thesis <- Distances()
plot.df <- DistancesPlot(dist.thesis)
plot.df$author <- "Lo Presti"
# change name "intestinal mucosa"
plot.df$sample_type <- as.character(plot.df$sample_type)
plot.df[plot.df$sample_type == "intestinal mucosa", 'sample_type'] <- "sigmoid mucosa"


p1 <- ggplot(plot.df[plot.df$sample_type == "stool" & plot.df$distance == "Weighted Unifrac",], aes(Axis.1, Axis.2, color=host_disease))+
  geom_point(size=12, alpha=0.4)  + scale_color_manual(values = c('blue', 'red'))+
  facet_grid(author~distance, scales='free')+
  theme_bw()+
  theme(axis.title = element_blank(),
        #axis.title.x = element_text(size = 40),
        axis.text = element_text(size = 30),
        legend.text = element_text(size = 40),
        legend.title = element_text(size = 40),
        strip.background = element_rect(fill = "white", size = 3),
        panel.border = element_rect(size = 2),
        #strip.text.x = element_text(size = 50, margin = margin(1,0,1,0, "cm")),
        strip.text.x = element_blank(),
        strip.text.y = element_text(size = 70, margin = margin(0,1,0,1, "cm")),
        #axis.line = element_line(size = 1, arrow = arrow(length = unit(0.1, "inches")))
        )+
  labs(color="Disease")

p2 <- ggplot(plot.df[plot.df$sample_type == "stool" & plot.df$distance != "Weighted Unifrac",], aes(Axis.1, Axis.2, color=host_disease))+
  geom_point(size=12, alpha=0.4)  + scale_color_manual(values = c('blue', 'red'))+
  facet_wrap(~distance, scales='free', nrow = 1)+
  guides(color = FALSE)+
  theme_bw()+
  theme(axis.text = element_text(size = 30),
        axis.title.y = element_text(size = 40),
        axis.title.x = element_blank(),
        strip.background = element_rect(fill = "white", size = 1),
        panel.border = element_rect(size = 2),
        #strip.text = element_text(size = 50, margin = margin(1,0,1,0, "cm")),
        strip.text.x = element_blank(),
        #axis.line = element_line(size = 1, arrow = arrow(length = unit(0.1, "inches")))
        )

library(ggplot2)
library(ggpubr)

jpeg("/Users/scarcy/Desktop/Praktikum/Thesis/dist_LoPresti.jpeg", height = 800, width = 4000, res = 100)
ggarrange(p2, p1, ncol = 2, widths = c(2,1))
dev.off()

# COLOR BY SAMPLE TYPE
p3 <- ggplot(plot.df[plot.df$distance == "Weighted Unifrac",], aes(Axis.1, Axis.2, color=sample_type))+
  geom_point(size=12, alpha=0.7)  + scale_color_manual(values = c('#CC00FF', '#66CC00'))+
  facet_grid(author~distance, scales='free')+
  theme_minimal()+
  theme(axis.title = element_blank(),
        axis.title.x = element_text(size = 40),
        axis.text = element_text(size = 30),
        legend.text = element_text(size = 40),
        legend.title = element_text(size = 40),
        strip.background = element_rect(size = 1),
        strip.text.x = element_text(size = 50, margin = margin(1,0,1,0, "cm")),
        #strip.text.x = element_blank(),
        strip.text.y = element_text(size = 50, margin = margin(0,1,0,1, "cm")),
        axis.line = element_line(size = 1, arrow = arrow(length = unit(0.1, "inches"))))+
  labs(color="Sample type")

p4 <- ggplot(plot.df[plot.df$distance != "Weighted Unifrac",], aes(Axis.1, Axis.2, color=sample_type))+
  geom_point(size=12, alpha=0.7)  + scale_color_manual(values = c('#CC00FF', '#66CC00'))+
  facet_wrap(~distance, scales='free', nrow = 1)+
  guides(color = FALSE)+
  theme_minimal()+
  theme(axis.text = element_text(size = 30),
        axis.title.y = element_text(size = 40),
        axis.title.x = element_text(size = 40),
        strip.background = element_rect(size = 1),
        strip.text = element_text(size = 50, margin = margin(1,0,1,0, "cm")),
        #strip.text.x = element_blank(),
        axis.line = element_line(size = 1, arrow = arrow(length = unit(0.1, "inches"))))

jpeg("/Users/scarcy/Desktop/Praktikum/Thesis/dist_LoPresti_sampleType.jpeg", height = 1000, width = 4000, res = 100)
ggarrange(p4, p3, ncol = 2, widths = c(1.75,1))
dev.off()

```

```{r dist-functions, eval = TRUE, echo = TRUE}
#____________________________________________________________________________________
# Measure distances
Distances <- function(physeq_obj){
  set.seed(123) # for unifrac, need to set a seed
  glom.UniF <-  UniFrac(physeq_obj, weighted=TRUE, normalized=TRUE) # weighted unifrac
  glom.ait <- dist(x = otu_table(physeq.clr), method = 'euc') # aitchison
  glom.bray <- phyloseq::distance(physeq_obj, method = "bray") # bray-curtis
  glom.can <- phyloseq::distance(physeq_obj, method = "canberra") # canberra
  dist.list <- list("UniF" = glom.UniF, "Ait" = glom.ait, "Canb" = glom.can, "Bray" = glom.bray)
  
  return(dist.list)
}


#____________________________________________________________________________________
# Plot 2D ordination
MDS_2D <- function(physeq_obj, ait_dist){
  
  plist <- NULL
  plist <- vector("list", length(dist_methods)+1) # save each plot to a list
  names(plist) <- dist_methods # save the name of each method
  names(plist)[17] <- "aitchison" # save the name of aitchison
  
  # Loop through all distance methods
  for(i in dist_methods){
    # Calculate distance matrix
    #print(i)
    set.seed(123) # in case the distance method needs a rooted tree (weighted unifrac)
    iDist <- phyloseq::distance(physeq_obj, method=i)
    # Calculate ordination
    set.seed(123)
    iMDS  <- ordinate(physeq_obj, "MDS", distance=iDist)
    ## Make plot
    # Don't carry over previous plot (if error, p will be blank)
    p <- NULL
    # Create plot, store as temporary variable, p
    p <- plot_ordination(physeq_obj, iMDS, color="host_disease")
    # Add title to each plot
    p <- p + ggtitle(paste("MDS using distance method ", i, sep=""))
    # Save the graphic to the plot list
    plist[[i]] = p
  }
  
  # Add aitchison
  iMDS  <- ordinate(physeq_obj, "MDS", distance=ait_dist)
  p <- NULL
  p <- plot_ordination(physeq_obj, iMDS, color="host_disease")
  p <- p + ggtitle("MDS using distance method Aitchison")
  plist[[17]] = p
  
  # Creating a dataframe to plot everything
  plot.df = ldply(plist, function(x) x$data)
  names(plot.df)[1] <- "distance"
  
  # Plot
  p.alldist <-  ggplot(plot.df, aes(Axis.1, Axis.2, color=host_disease))+
    geom_point(size=5, alpha=0.5)+
    facet_wrap(~distance, scales='free')+
    theme(strip.text = element_text(size = 40),
          legend.text = element_text(size = 20),
          axis.text.x = element_text(size = 20),
          axis.text.y = element_text(size = 20))

  return(p.alldist)
}

#____________________________________________________________________________________
# Plot 3D ordination
MDS_3D <- function(d, name_dist){
  
  # Reset parameters
  mds.3D <- NULL
  xyz <- NULL
  fig.3D <- NULL
  
  # Reduce distance matrix to 3 dimensions
  set.seed(123) # to get the same dimensionality reduction at each run
  mds.3D <- metaMDS(d, method="MDS", k=3, trace = 0)
  xyz <- scores(mds.3D, display="sites") # pull out the x y z coordinates
  
  fig.3D <- plot_ly(x=xyz[,1], y=xyz[,2], z=xyz[,3], type="scatter3d", mode="markers",
                    color=sample_data(physeq.rel)$env_material, colors = c('#CC00FF', '#66CC00'))%>%
    #add_trace(x=xyz[,1], y=xyz[,2], z=xyz[,3],
    #       type='scatter3d', mode='text', text = rownames(xyz), textfont = list(color = "black")) %>%
    layout(title = paste('MDS in 3D with', name_dist, 'distance', sep = ' '))
  
  return(fig.3D)
}

```


```{r no-glom1, fig.height = 20, fig.width = 30}
# Get the distances
no_glom.dist <- Distances(physeq_obj = physeq.rel)

# Get the 2D ordination plots
no_glom.2D.alldist <- MDS_2D(physeq.rel, no_glom.dist$Ait)
no_glom.2D.alldist + scale_color_manual(values = c('blue', 'red'))
```

```{r plot-2D-ordination-sampleType, fig.height = 20, fig.width = 30}
# Plot 2D ordination
MDS_2D_sampleType <- function(physeq_obj, ait_dist){
  
  plist <- NULL
  plist <- vector("list", length(dist_methods)+1) # save each plot to a list
  names(plist) <- dist_methods # save the name of each method
  names(plist)[17] <- "aitchison" # save the name of aitchison
  
  # Loop through all distance methods
  for(i in dist_methods){
    # Calculate distance matrix
    #print(i)
    set.seed(123) # in case the distance method needs a rooted tree (weighted unifrac)
    iDist <- phyloseq::distance(physeq_obj, method=i)
    # Calculate ordination
    set.seed(123)
    iMDS  <- ordinate(physeq_obj, "MDS", distance=iDist)
    ## Make plot
    # Don't carry over previous plot (if error, p will be blank)
    p <- NULL
    # Create plot, store as temporary variable, p
    p <- plot_ordination(physeq_obj, iMDS, color="env_material")
    # Add title to each plot
    p <- p + ggtitle(paste("MDS using distance method ", i, sep=""))
    # Save the graphic to the plot list
    plist[[i]] = p
  }
  
  # Add aitchison
  iMDS  <- ordinate(physeq_obj, "MDS", distance=ait_dist)
  p <- NULL
  p <- plot_ordination(physeq_obj, iMDS, color="env_material")
  p <- p + ggtitle("MDS using distance method Aitchison")
  plist[[17]] = p
  
  # Creating a dataframe to plot everything
  plot.df = ldply(plist, function(x) x$data)
  names(plot.df)[1] <- "distance"
  
  # Plot
  p.alldist <-  ggplot(plot.df, aes(Axis.1, Axis.2, color=env_material))+
    geom_point(size=5, alpha=0.5)+
    facet_wrap(~distance, scales='free')+
    theme(strip.text = element_text(size = 40),
          legend.text = element_text(size = 20),
          axis.text.x = element_text(size = 20),
          axis.text.y = element_text(size = 20))

  return(p.alldist)
}


sampleType.2D.alldist <- MDS_2D_sampleType(physeq.rel, no_glom.dist$Ait)
sampleType.2D.alldist + scale_color_manual(values = c('#CC00FF', '#66CC00'))
```


```{r plot-2D-ordination-subtypes, fig.height = 20, fig.width = 30}
# Plot 2D ordination
MDS_2D_subtypes <- function(physeq_obj, ait_dist){
  
  plist <- NULL
  plist <- vector("list", length(dist_methods)+1) # save each plot to a list
  names(plist) <- dist_methods # save the name of each method
  names(plist)[17] <- "aitchison" # save the name of aitchison
  
  # Loop through all distance methods
  for(i in dist_methods){
    # Calculate distance matrix
    #print(i)
    set.seed(123) # in case the distance method needs a rooted tree (weighted unifrac)
    iDist <- phyloseq::distance(physeq_obj, method=i)
    # Calculate ordination
    set.seed(123)
    iMDS  <- ordinate(physeq_obj, "MDS", distance=iDist)
    ## Make plot
    # Don't carry over previous plot (if error, p will be blank)
    p <- NULL
    # Create plot, store as temporary variable, p
    p <- plot_ordination(physeq_obj, iMDS, color="gastrointest_disord")
    # Add title to each plot
    p <- p + ggtitle(paste("MDS using distance method ", i, sep=""))
    # Save the graphic to the plot list
    plist[[i]] = p
  }
  
  # Add aitchison
  iMDS  <- ordinate(physeq_obj, "MDS", distance=ait_dist)
  p <- NULL
  p <- plot_ordination(physeq_obj, iMDS, color="gastrointest_disord")
  p <- p + ggtitle("MDS using distance method Aitchison")
  plist[[17]] = p
  
  # Creating a dataframe to plot everything
  plot.df = ldply(plist, function(x) x$data)
  names(plot.df)[1] <- "distance"
  
  # Plot
  p.alldist <-  ggplot(plot.df, aes(Axis.1, Axis.2, color=gastrointest_disord))+
    geom_point(size=5, alpha=0.5)+
    facet_wrap(~distance, scales='free')+
    theme(strip.text = element_text(size = 40),
          legend.text = element_text(size = 20),
          axis.text.x = element_text(size = 20),
          axis.text.y = element_text(size = 20))

  return(p.alldist)
}


subtypes.2D.alldist <- MDS_2D_subtypes(physeq.rel, no_glom.dist$Ait)
subtypes.2D.alldist + scale_color_manual(values = c('black', '#6600FF', '#00CC66', '#FF6633'))
```


```{r save-distances, eval = FALSE, echo = FALSE}
getwd()

write.csv(as.matrix(no_glom.dist$UniF), file = "dist_wunifrac.csv", row.names = TRUE)
write.csv(as.matrix(no_glom.dist$Ait), file = "dist_aitchison.csv", row.names = TRUE)
write.csv(as.matrix(no_glom.dist$Canb), file = "dist_canberra.csv", row.names = TRUE)

```



```{r no-glom2, fig.height = 6, fig.width = 10, eval = FALSE, echo = TRUE}
# Get 3D MDS plots
no_glom.3D.UniF <- MDS_3D(no_glom.dist$UniF, 'weighted Unifrac')
no_glom.3D.Ait <- MDS_3D(no_glom.dist$Ait, 'Aitchison')
no_glom.3D.Can <- MDS_3D(no_glom.dist$Canb, 'Canberra')
no_glom.3D.Bray <- MDS_3D(no_glom.dist$Bray, 'Bray-Curtis')

no_glom.3D.UniF
no_glom.3D.Ait
no_glom.3D.Can
no_glom.3D.Bray
```



#############################
## HIERARCHICAL CLUSTERING ##
#############################

```{r hierarchical-clust, fig.width = 10, fig.width = 7}
Heatmaps <- function(dist_list, fontsize){
  # Weighted Unifrac
  heatmp.UniF <- pheatmap(as.matrix(dist_list$UniF), 
                          clustering_distance_rows = dist_list$UniF,
                          clustering_distance_cols = dist_list$UniF,
                          fontsize = fontsize,
                          fontsize_col = fontsize-5,
                          fontsize_row = fontsize-5,
                          annotation_col = mat_col,
                          annotation_row = mat_col,
                          annotation_colors = list(group = c('Healthy' = 'blue', 'IBS' = 'red'),
                                                   sampleType = c('intestinal mucosa' = '#CC00FF', 'stool' = '#66CC00'),
                                                   subtype = c('HC'='black', 'IBS-A'='#6600FF',
                                                               'IBS-C'='#00CC66', 'IBS-D'='#FF6633')),
                          cluster_rows = T,
                          cluster_cols = T,
                          clustering_method = 'complete', #hierarchical method
                          main = 'Weighted unifrac distance')

  # Aitchison
  heatmp.Ait <- pheatmap(as.matrix(dist_list$Ait), 
                         clustering_distance_rows = dist_list$Ait,
                         clustering_distance_cols = dist_list$Ait,
                         fontsize = fontsize,
                         fontsize_col = fontsize-5,
                         fontsize_row = fontsize-5,
                         # border_color = NA,
                         cluster_rows = T,
                         cluster_cols = T,
                         clustering_method = "complete", #hierarchical method
                         annotation_col = mat_col,
                         annotation_row = mat_col,
                         annotation_colors = list(group = c('Healthy' = 'blue', 'IBS' = 'red'),
                                                   sampleType = c('intestinal mucosa' = '#CC00FF', 'stool' = '#66CC00'),
                                                   subtype = c('HC'='black', 'IBS-A'='#6600FF',
                                                               'IBS-C'='#00CC66', 'IBS-D'='#FF6633')),
                         main = "Aitchison distance")
  
    # Canberra
  heatmp.Can <- pheatmap(as.matrix(dist_list$Can), 
                         clustering_distance_rows = dist_list$Can,
                         clustering_distance_cols = dist_list$Can,
                         fontsize = fontsize,
                         fontsize_col = fontsize-5,
                         fontsize_row = fontsize-5,
                         # border_color = NA,
                         cluster_rows = T,
                         cluster_cols = T,
                         clustering_method = "complete", #hierarchical method
                         annotation_col = mat_col,
                         annotation_row = mat_col,
                         annotation_colors = list(group = c('Healthy' = 'blue', 'IBS' = 'red'),
                                                   sampleType = c('intestinal mucosa' = '#CC00FF', 'stool' = '#66CC00'),
                                                   subtype = c('HC'='black', 'IBS-A'='#6600FF',
                                                               'IBS-C'='#00CC66', 'IBS-D'='#FF6633')),
                         main = "Canberra distance")
  
  # Bray-Curtis
  heatmp.Bray <- pheatmap(as.matrix(dist_list$Bray), 
                         clustering_distance_rows = dist_list$Bray,
                         clustering_distance_cols = dist_list$Bray,
                         fontsize = fontsize,
                         fontsize_col = fontsize-5,
                         fontsize_row = fontsize-5,
                         # border_color = NA,
                         cluster_rows = T,
                         cluster_cols = T,
                         clustering_method = "complete", #hierarchical method
                         annotation_col = mat_col,
                         annotation_row = mat_col,
                         annotation_colors = list(group = c('Healthy' = 'blue', 'IBS' = 'red'),
                                                   sampleType = c('intestinal mucosa' = '#CC00FF', 'stool' = '#66CC00'),
                                                   subtype = c('HC'='black', 'IBS-A'='#6600FF',
                                                               'IBS-C'='#00CC66', 'IBS-D'='#FF6633')),
                         main = "Bray-Curtis distance")
  
  return(list("UniF" = heatmp.UniF, "Ait" = heatmp.Ait, "Can" = heatmp.Can, "Bray" = heatmp.Bray))
}


# Get the heatmaps
no_glom.heatmaps <- Heatmaps(dist_list = no_glom.dist, fontsize = 8)
```



```{r export-plots-2, eval = FALSE, echo = FALSE}
# MDS 2D all distances
jpeg("./Plots/AllDistances_MDS.jpg", width = 3000, height = 2000, res = 90)
no_glom.2D.alldist +
  scale_color_manual(values = c('blue', 'red'))+
  theme(axis.text.x = element_text(size = 20),
        legend.text = element_text(size = 50),
        axis.title = element_text(size = 50),
        title = element_text(size = 50),
        strip.text = element_text(size = 50))+
  labs(title = "LoPresti dataset (2019)")
dev.off()

jpeg("./Plots/AllDistances_MDS_sampleType.jpg", width = 3000, height = 2000, res = 90)
sampleType.2D.alldist +
  scale_color_manual(values = c('#CC00FF', '#66CC00'))+
  theme(axis.text.x = element_text(size = 20),
        legend.text = element_text(size = 50),
        axis.title = element_text(size = 50),
        title = element_text(size = 70),
        strip.text = element_text(size = 50))+
  labs(title = "LoPresti dataset (2019)")
dev.off()

jpeg("./Plots/AllDistances_MDS_subtypes.jpg", width = 3000, height = 2000, res = 90)
subtypes.2D.alldist +
  scale_color_manual(values = c('black', '#6600FF', '#00CC66', '#FF6633'))+
  theme(axis.text.x = element_text(size = 20),
        legend.text = element_text(size = 50),
        axis.title = element_text(size = 50),
        title = element_text(size = 50),
        strip.text = element_text(size = 50))
dev.off()


# Heatmaps
jpeg("./Plots/plot_heatmap_aitchison.jpg", width = 1400, height = 1000, res = 150)
no_glom.heatmaps$Ait
dev.off()

jpeg("./Plots/plot_heatmap_UniF.jpg", width = 1400, height = 1000, res = 150)
no_glom.heatmaps$UniF
dev.off()

jpeg("./Plots/plot_heatmap_canberra.jpg", width = 1400, height = 1000, res = 150)
no_glom.heatmaps$Can
dev.off()

jpeg("./Plots/plot_heatmap_bray.jpg", width = 1400, height = 1000, res = 150)
no_glom.heatmaps$Bray
dev.off()

```


################################
## REPRODUCE PLOTS FROM PAPER ##
################################

```{r reproduce-plots, fig.width = 7}
# Stool samples
stool.table <- subset_samples(physeq_best, env_material == "stool") %>%
  tax_glom(taxrank = "Phylum") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt()                                             # Melt to long format

stool.table$host_disease <- factor(stool.table$host_disease, levels = c('IBS', 'Healthy')) # have same order as paper

ggplot(stool.table, aes(x = host_disease, y = Abundance, fill = Phylum))+
  geom_bar(stat = "identity", position = "fill") +
  theme(axis.text.x = element_text(size = 8))+
  labs(x = "Samples", y = "Relative abundance", title = "Stool samples")

# Mucosa samples
mucosa.table <- subset_samples(physeq_best, env_material == "intestinal mucosa") %>%
  tax_glom(taxrank = "Phylum") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt()                                             # Melt to long format

mucosa.table$host_disease <- factor(mucosa.table$host_disease, levels = c('IBS', 'Healthy')) # have same order as paper

ggplot(mucosa.table, aes(x = host_disease, y = Abundance, fill = Phylum))+
  geom_bar(stat = "identity", position = "fill") +
  theme(axis.text.x = element_text(size = 8))+
  labs(x = "Samples", y = "Relative abundance", title = "Intestinal mucosa samples")
```


```{r export-plots-3, eval = FALSE, echo = FALSE}
jpeg("./Plots/fig1_stool.jpg", height = 1600, width = 1500, res = 300)
ggplot(stool.table, aes(x = host_disease, y = Abundance, fill = Phylum))+
  geom_bar(stat = "identity", position = "fill") +
  theme(axis.text.x = element_text(size = 8))+
  labs(y = "Relative abundance", title = "Stool samples")
dev.off()

jpeg("./Plots/fig3_mucosa.jpg", height = 1600, width = 1500, res = 300)
ggplot(mucosa.table, aes(x = host_disease, y = Abundance, fill = Phylum))+
  geom_bar(stat = "identity", position = "fill") +
  theme(axis.text.x = element_text(size = 8))+
  labs(y = "Relative abundance", title = "Intestinal mucosa samples")
dev.off()
```





```{r}
# Function that will allow to color the leaves of the tree according to sample type (biopsy vs stool)
color_leaf<<-function(n){
    if(is.leaf(n)){
        # take the current attributes
        a=attributes(n)
        
        # deduce the line in the original data, to get the corresponding sampleType status
        line=match(attributes(n)$label, plot.df$Run)
        sampleType=plot.df[line, "sample_type"];
            if(sampleType=="sigmoid mucosa"){col_sampleType="#CC00FF"};if(sampleType=="stool"){col_sampleType="#66CC00"}
        
        #Modification of leaf attribute
        attr(n,"nodePar") <- c(a$nodePar, list(cex=1.5, lab.cex=0.6, pch=20, col=col_sampleType, lab.font=1, lab.cex=1))
        }
    return(n)
}


plot.df
```

```{r fig.height = 3}
hc.ward <- hclust(dist.thesis$Ait, method = "ward.D") #clustering 
dend.ward <- as.dendrogram(hc.ward) # Make into dendograms

dend.ward <- dendrapply(dend.ward, color_leaf) # Apply the color attributes to the dendograms

jpeg("/Users/scarcy/Desktop/Praktikum/Thesis/hclust_lopresti.jpg", height = 2000, width = 1000, res = 200)
plot(dend.ward , main="Hierarchical clustering on Aitchison distance (ward linkage)", horiz = TRUE, leaflab = "none",
     edgePar = list(lwd = 1))
axis(side = 1, lwd = 4)
legend(50, 64, 
     legend = c("Sigmoid mucosa" , "Stool"), 
     col = c("#CC00FF", "#66CC00"), 
     pch = c(20,20), bty = "n",  pt.cex = 1.5, cex = 1, 
     text.col = "black", horiz = FALSE, inset = c(0, 0.1))
dev.off()
```

