---
title: "UMAP"
output: html_notebook
---


##########
# IMPORT #
##########

## Import libraries

```{r import-libraries, echo = FALSE}
library(phyloseq)
library(ggplot2)
library(umap)
library(tidyverse)
library(reshape2)
library(gtools)
```


## Import data

```{r import-data}
path.phy <- "~/Projects/IBS_Meta-analysis_16S/data/analysis-individual/CLUSTER/PhyloTree/input"

# Import phyloseq objects
physeq.ringel <- readRDS(file.path(path.phy, "physeq_ringel.rds"))
physeq.labus <- readRDS(file.path(path.phy, "physeq_labus.rds"))
physeq.lopresti <- readRDS(file.path(path.phy, "physeq_lopresti.rds"))
physeq.pozuelo <- readRDS(file.path(path.phy, "physeq_pozuelo.rds"))
physeq.zhuang <- readRDS(file.path(path.phy, "physeq_zhuang.rds"))
physeq.zhu <- readRDS(file.path(path.phy, "physeq_zhu.rds"))
physeq.hugerth <- readRDS(file.path(path.phy, "physeq_hugerth.rds"))
physeq.fukui <- readRDS(file.path(path.phy, "physeq_fukui.rds"))
physeq.mars <- readRDS(file.path(path.phy, "physeq_mars.rds"))
physeq.liu <- readRDS(file.path(path.phy, "physeq_liu.rds"))
physeq.agp <- readRDS(file.path(path.phy, "physeq_agp.rds"))
physeq.nagel <- readRDS(file.path(path.phy, "physeq_nagel.rds"))
physeq.zeber <- readRDS(file.path(path.phy, "physeq_zeber.rds"))

# Little changes
# sample_data(physeq.labus)[sample_data(physeq.labus)$host_disease == "None","host_disease"] <- "Healthy"
# sample_data(physeq.labus)$sample_type <- "stool"
# sample_data(physeq.zhu)$sample_type <- "stool"

# Sanity checks
# table(tax_table(physeq.zeber)[,1])
# table(is.na(tax_table(physeq.zeber)[,2]))
# table(sample_sums(physeq.zeber)<500)
```



##################
# MERGE DATASETS #
##################

## Merge datasets

```{r merge-datasets}
# Merge phyloseq objects
colnames(sample_data(physeq.hugerth))[5] <- "host_sex"
colnames(sample_data(physeq.lopresti))[6] <- "host_subtype"
physeq <- merge_phyloseq(physeq.ringel,
                         physeq.labus,
                         physeq.lopresti,
                         physeq.pozuelo,
                         physeq.zhuang,
                         physeq.zhu,
                         physeq.hugerth,
                         physeq.fukui,
                         physeq.mars,
                         physeq.liu,
                         physeq.agp,
                         physeq.nagel,
                         physeq.zeber)

# Adjust sample_data
colnames(sample_data(physeq))
#sample_data(physeq)[is.na(sample_data(physeq)$sample_type), 'sample_type'] <- 'stool'
sample_data(physeq)[is.na(sample_data(physeq)$host_disease), "host_disease"] <- "NA"
sample_data(physeq)[is.na(sample_data(physeq)$host_sex), "host_sex"] <- "unknown"
sample_data(physeq)[sample_data(physeq)$host_disease == "Healthy", "host_subtype"] <- "HC"
sample_data(physeq)[sample_data(physeq)$host_disease == "NA", "host_subtype"] <- "NA"
sample_data(physeq)[is.na(sample_data(physeq)$host_subtype), "host_subtype"] <- "IBS-unspecified"
sample_data(physeq)[sample_data(physeq)$author %in% c("Zhuang", "Zhu", "Hugerth", "Fukui", "Mars"), "sequencing_tech"] <- "Illumina MiSeq paired-end"
sample_data(physeq)[sample_data(physeq)$author %in% c("Pozuelo", "Liu", "AGP"), "sequencing_tech"] <- "Illumina MiSeq single-end"

# check on sample_data
sample_data(physeq)
table(sample_data(physeq)$author, useNA="ifany") #ok
table(sample_data(physeq)$sequencing_tech, useNA="ifany") #ok
table(sample_data(physeq)$variable_region, useNA="ifany") # ok
table(sample_data(physeq)$host_disease, useNA="ifany") # ok
table(sample_data(physeq)$host_sex, useNA="ifany") # ok

table(sample_data(physeq)$host_age, useNA="ifany") # ok
table(sample_data(physeq)$host_bmi, useNA="ifany") # ok
table(sample_data(physeq)$host_subtype, useNA="ifany") # ok
table(sample_data(physeq)$sample_type, useNA="ifany") # ok

```


## Normalize data

```{r normalize}
# Keep only fecal samples
physeq.fecal <- subset_samples(physeq, sample_type == 'stool') # 2,245 samples
physeq.sigmoid <- subset_samples(physeq, sample_type == 'sigmoid') # 431 samples

# Have pseudocounts
physeq.pseudocts <- physeq.fecal
otu_table(physeq.pseudocts)[otu_table(physeq.pseudocts) == 0] <- 0.5

# Get non-zero compositions
# physeq.NZcomp <- physeq.fecal
# otu_table(physeq.NZcomp)[otu_table(physeq.NZcomp) == 0] <- 0.5 # pseudocounts
# physeq.NZcomp <- transform_sample_counts(physeq.NZcomp, function(x) x / sum(x) )
# table(rowSums(otu_table(physeq.NZcomp))) # check if there is any row not summing to 1
```


########
# UMAP #
########

## FUNCTIONS

This function takes an abundance matrix (taxa as rows, samples as columns) and computes all pairwise log ratios.

```{r functions}
#________________________
# LOG-RATIOS

LogRatios <- function(abundanceTable){
  
  # Get combinations between all taxa
  comb <- as.data.frame(combinations(nrow(abundanceTable), 2, rownames(abundanceTable), repeats.allowed = FALSE))
  comb[,3] <- paste0(comb[,1], "/", comb[,2])
  # cat("First 5 combinations:\n")
  # comb[1:5,]
  
  cat("Number of combinations:", nrow(comb), "\n")

  # Compute the ratios
  ratios <- as.data.frame(abundanceTable) # taxa as rows, samples as columns
  test <- ratios[1:3,1:3] # for later sanity check
  
  ratios[ comb[,3] ,] <- mapply(function(x, y) log2(x/y), # compute the log ratio
                                abundanceTable[ as.character(comb[,1]) ,], # between first column
                                abundanceTable[ as.character(comb[,2]) ,]) # and second column of all combinations

  ratios <- ratios[-c(1:nrow(abundanceTable)),] # remove first x rows that are not ratios (it is simply the phyla)
  cat("Sanity check: log-ratio is", log2(test[1,1]/test[2,1]),
      "and the corresponding value in the log-ratio table is", ratios[1,1], "\n")
  cat("Sanity check2: log-ratio is", log2(test[1,2]/test[3,2]),
      "and the corresponding value in the log-ratio table is", ratios[2,2], "\n") # sanity check
  
  cat("We have", dim(ratios)[2], "samples and", dim(ratios)[1], "predictors (log-ratios) \n")

  # Return table with samples as rows and logratios as columns
  return(t(ratios))
}
```
```

