---
title: "Taxonomy-Tree"
output: html_notebook
---


##########
# IMPORT #
##########

## Import libraries

```{r import-libraries, echo = FALSE}
library(phyloseq)
library(ggplot2)
library(umap)
library(tidyverse)
library(reshape2)
library(gtools)
```


## Import data

```{r import-data}
path.phy <- "~/Projects/IBS_Meta-analysis_16S/data/analysis-individual/CLUSTER/PhyloTree/input"

# Import phyloseq objects
physeq.ringel <- readRDS(file.path(path.phy, "physeq_ringel.rds"))
physeq.labus <- readRDS(file.path(path.phy, "physeq_labus.rds"))
physeq.lopresti <- readRDS(file.path(path.phy, "physeq_lopresti.rds"))
physeq.pozuelo <- readRDS(file.path(path.phy, "physeq_pozuelo.rds"))
physeq.zhuang <- readRDS(file.path(path.phy, "physeq_zhuang.rds"))
physeq.zhu <- readRDS(file.path(path.phy, "physeq_zhu.rds"))
physeq.hugerth <- readRDS(file.path(path.phy, "physeq_hugerth.rds"))
physeq.fukui <- readRDS(file.path(path.phy, "physeq_fukui.rds"))
physeq.mars <- readRDS(file.path(path.phy, "physeq_mars.rds"))
physeq.liu <- readRDS(file.path(path.phy, "physeq_liu.rds"))
physeq.agp <- readRDS(file.path(path.phy, "physeq_agp.rds"))
physeq.nagel <- readRDS(file.path(path.phy, "physeq_nagel.rds"))
physeq.zeber <- readRDS(file.path(path.phy, "physeq_zeber.rds"))

# Little changes
# sample_data(physeq.labus)[sample_data(physeq.labus)$host_disease == "None","host_disease"] <- "Healthy"
# sample_data(physeq.labus)$sample_type <- "stool"
# sample_data(physeq.zhu)$sample_type <- "stool"

# Sanity checks
# table(tax_table(physeq.zeber)[,1])
# table(is.na(tax_table(physeq.zeber)[,2]))
# table(sample_sums(physeq.zeber)<500)
```



##################
# MERGE DATASETS #
##################

```{r merge-datasets}
# Merge phyloseq objects
physeq <- merge_phyloseq(physeq.ringel,
                         physeq.labus,
                         physeq.lopresti,
                         physeq.pozuelo,
                         physeq.zhuang,
                         physeq.zhu,
                         physeq.hugerth,
                         physeq.fukui,
                         physeq.mars,
                         physeq.liu,
                         physeq.agp,
                         physeq.nagel,
                         physeq.zeber)

# check on sample_data
colnames(sample_data(physeq))
table(sample_data(physeq)$author, useNA="ifany") #ok
table(sample_data(physeq)$sequencing_tech, useNA="ifany") #ok
table(sample_data(physeq)$variable_region, useNA="ifany") # ok

table(sample_data(physeq)$host_disease, useNA="ifany") # ok
table(sample_data(physeq)$host_subtype, useNA="ifany") # ok
table(sample_data(physeq)$sample_type, useNA="ifany") # ok

table(sample_data(physeq)$host_sex, useNA="ifany") # ok
table(sample_data(physeq)$host_age, useNA="ifany") # ok
table(sample_data(physeq)$host_bmi, useNA="ifany") # ok
table(sample_data(physeq)$Collection, useNA="ifany") # ok
```


#############
# PLOT TREE #
#############

```{r}
plot_tree(physeq, color="Phylum")
taxo.eg[[1]]
```

# Taxo2phylog

```{r}
# Example given
library(ade4)
data(taxo.eg)
taxo.eg[[1]]
tax <- as.taxo(taxo.eg[[1]])

tax.phy <- taxo2phylog(as.taxo(taxo.eg[[1]]))
print(tax.phy)

#Plot
ggtree(tax.phy, layout="circular") + geom_tiplab() + geom_nodelab(geom='label')


#__________________
tax <- as.data.frame(physeq.labus@tax_table@.Data, stringsAsFactors = TRUE)
tax$Kingdom <- NULL
tax$Species <- NULL
as.taxo(tax[,1:2]) # problem

tax.phy <- taxo2phylog(tax)

```



1) convert taxonomic table to newick string
2) plot with ggtree
