---
title: "00_Metadata-Liu"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
---


```{r, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE,
                      root.dir = "~/Projects/MetaIBS/data/analysis-individual/Liu-2020/00_Metadata-Liu/")
```




***********
# 1. IMPORT
***********

## 1.1. Libraries
```{r import-libraries}
library(data.table)
library(tidyverse)
```

## 1.2. Data
```{r import-data}
path.root <- "~/Projects/MetaIBS" # CHANGE THIS PATH ON YOUR COMPUTER
path.scripts <- file.path(path.root, "scripts/analysis-individual/Liu-2020")
path.data    <- file.path(path.root, "data/analysis-individual/Liu-2020")

# Metadata table downloaded from the SRA
sra_metadata <- read.csv(file.path(path.data, "00_Metadata-Liu/LiuSraRunTable.txt"), header=TRUE, sep = ",")
head(sra_metadata)
```




******************
# 2. CLEANUP TABLE
******************

```{r cleanup-metadata}
clean.df <- sra_metadata %>%
  # Select relevant columns
  select(all_of(c("Run","Isolation_source", "sex", "AGE", "BMI", "Bristol", "IBS_SSS", "Collection_date"))) %>%
  # Reformat DF
  rename(host_subtype = Isolation_source,
         host_sex = sex,
         host_age = AGE,
         host_bmi = BMI,
         collection_date = Collection_date) %>%
  mutate(host_disease = replace(host_subtype, host_subtype=="HC", "Healthy")) %>%
  mutate(sample_type = "stool") %>%
  relocate(host_disease, .after=Run) %>%
  relocate(host_subtype, .after=IBS_SSS)

head(clean.df)
```




******************
# 3. SAVE METADATA
******************

```{r save-data, echo=TRUE, eval=FALSE}
# Export metadata table
write.csv(clean.df, file.path(path.data, "00_Metadata-Liu/modif_metadata(R).csv"))

# Export the list of Runs to download
write.table(clean.df$Run, file.path(path.scripts, "download-Liu-samples/list_files_liu.txt"),
            sep="\t", row.names=FALSE, col.names=FALSE, quote=FALSE)
```




*****************
# 4. SESSION INFO
*****************

```{r session-info}
sessionInfo()
```